spring.application.name=parking-service

parking.provider=poitiers
parking.providers.poitiers.base-url=https://data.grandpoitiers.fr
parking.providers.poitiers.dataset-path=/data-fair/api/v1/datasets/mobilites-stationnement-des-parkings-en-temps-reel/lines
parking.providers.poitiers.connect-timeout=2s
parking.providers.poitiers.read-timeout=3s

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
server.error.include-message=never

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
